import Link from 'next/link';
import { Shield } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service — TrustArchive',
  description: 'TrustArchive terms of service, license agreement, and usage policy.',
};

const sections = [
  {
    title: '1. Acceptance of Terms',
    body: 'By purchasing or using TrustArchive, you agree to these Terms of Service. If you are using TrustArchive on behalf of a firm or organization, you represent that you have authority to bind that organization to these terms.',
  },
  {
    title: '2. License Grant',
    body: 'TrustArchive grants you a non-exclusive, non-transferable license to install and use the software on the number of machines permitted by your license tier. Your license is personal to you and may not be shared, sublicensed, or transferred without written consent.',
  },
  {
    title: '3. Subscription and Billing',
    body: 'TrustArchive is sold as an annual subscription. Your subscription renews automatically each year unless cancelled before the renewal date. You will receive email reminders 30 and 7 days before renewal. You may cancel auto-renewal at any time through your billing portal — your access continues through the end of your paid period. A 30-day free trial is available for new subscribers. Your payment method will be charged at the end of the trial period unless you cancel before day 30.',
  },
  {
    title: '4. Refunds',
    body: 'Refund requests within 14 days of initial purchase or renewal will be considered on a case-by-case basis. Contact us at support@trustarchive.co. We do not offer refunds after 14 days.',
  },
  {
    title: '5. Your Data',
    body: 'TrustArchive stores all data locally on your machine. We do not have access to your trust data, beneficiary records, financial information, or any other content you enter into the software. You are solely responsible for backing up your data. We are not liable for data loss resulting from hardware failure, accidental deletion, or failure to maintain backups.',
  },
  {
    title: '6. Permitted Use',
    body: 'TrustArchive is intended for lawful trust administration purposes. You agree not to use the software for any unlawful purpose, to reverse engineer the software, or to attempt to circumvent license enforcement mechanisms.',
  },
  {
    title: '7. No Professional Advice',
    body: 'TrustArchive is a software tool. It does not provide legal, tax, accounting, or financial advice. You are responsible for ensuring your trust administration practices comply with applicable law. Consult qualified legal and financial professionals for advice specific to your situation.',
  },
  {
    title: '8. Disclaimer of Warranties',
    body: 'TrustArchive is provided "as is" without warranty of any kind. We do not warrant that the software will be error-free or that it will meet your specific requirements. Your use of the software is at your own risk.',
  },
  {
    title: '9. Limitation of Liability',
    body: 'To the maximum extent permitted by law, TrustArchive and its developers shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the software, including but not limited to loss of data, loss of profits, or damages arising from reliance on outputs generated by the software.',
  },
  {
    title: '10. Changes to These Terms',
    body: 'We may update these terms from time to time. We will notify you of material changes via email at least 30 days before they take effect. Continued use of TrustArchive after that date constitutes acceptance of the updated terms.',
  },
  {
    title: '11. Governing Law',
    body: 'These terms are governed by the laws of the State of Tennessee, without regard to conflict of law principles.',
  },
  {
    title: '12. Contact',
    body: 'Questions about these terms: support@trustarchive.co',
  },
];

export default function TermsPage() {
  return (
    <div>
      <div style={{ paddingTop: 60 }}>
        <div className="page-hero">
          <div className="container">
            <span className="tag" style={{ marginBottom: 20, display: 'inline-flex' }}>
              <Shield size={11} /> Legal
            </span>
            <h1>Terms of Service</h1>
            <p>Effective Date: April 8, 2026</p>
          </div>
        </div>
      </div>

      <section className="section">
        <div className="container">
          <div style={{ maxWidth: 720, margin: '0 auto' }}>

            <div style={{
              background: 'var(--bg-surface)',
              border: '1px solid var(--accent-border)',
              borderRadius: 'var(--radius-lg)',
              padding: '20px 28px',
              marginBottom: 48,
              display: 'flex',
              gap: 14,
              alignItems: 'flex-start',
            }}>
              <Shield size={18} color="var(--accent)" style={{ flexShrink: 0, marginTop: 2 }} />
              <p style={{ fontSize: 14, color: 'var(--text-2)', lineHeight: 1.7, margin: 0 }}>
                TrustArchive is designed so that we never have access to your trust data.
                All financial records, beneficiary information, and documents stay on your machine.
                These terms govern your license to use the software, not any data we hold on your behalf.
              </p>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 40 }}>
              {sections.map(({ title, body }) => (
                <div key={title}>
                  <h2 style={{
                    fontSize: 16,
                    fontWeight: 700,
                    color: 'var(--text-1)',
                    marginBottom: 10,
                    paddingBottom: 10,
                    borderBottom: '1px solid var(--border)',
                  }}>{title}</h2>
                  <p style={{ fontSize: 14, color: 'var(--text-2)', lineHeight: 1.8 }}>{body}</p>
                </div>
              ))}
            </div>

            <div style={{
              marginTop: 64,
              paddingTop: 32,
              borderTop: '1px solid var(--border)',
              display: 'flex',
              gap: 24,
              flexWrap: 'wrap',
            }}>
              <Link href="/privacy" style={{ fontSize: 13, color: 'var(--accent)' }}>Privacy Policy →</Link>
              <Link href="/contact" style={{ fontSize: 13, color: 'var(--text-3)' }}>Contact Us</Link>
            </div>

          </div>
        </div>
      </section>
    </div>
  );
}
